jwt:
    expiration: 36000
    secret: secret
spring:
    data:
        mongodb:
            database: citas
            host: localhost
            port: 27017
    jpa:
        hibernate:
            use-new-id-generator-mappings: true
    main:
        allow-circular-references: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
